# Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# For reproducibility
np.random.seed(42)

print("Libraries imported successfully!")

Libraries imported successfully!

# Load the One-Hot Encoded Dataset

In [2]:
from pathlib import Path

# Get project root directory
BASE_DIR = Path.cwd().parent

# Path to Day 2 dataset
file_path = BASE_DIR / "Day 2" / "features_v1.csv"

# Load dataset
df = pd.read_csv(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_Male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1.0,0,A/5 21171,7.2500,Unknown,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1.0,0,PC 17599,65.6344,C85,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0.0,0,STON/O2. 3101282,7.9250,Unknown,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1.0,0,113803,53.1000,C123,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0.0,0,373450,8.0500,Unknown,True,False,True

In [4]:
print("Dataset Shape:", df.shape)

Dataset Shape: (891, 13)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    float64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    str
 8   Fare         891 non-null    float64
 9   Cabin        891 non-null    str
 10  Sex_Male     891 non-null    bool
 11  Embarked_Q   891 non-null    bool
 12  Embarked_S   891 non-null    bool
dtypes: bool(3), float64(3), int64(4), str(3)
memory usage: 72.3 KB

In [6]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Sex_Male,Embarked_Q,Embarked_S
count,891.000000,891.000000,891.000000,891,891.000000,891.000000,891.0,891,891.000000,891,891,891,891
unique,NaN,NaN,NaN,891,NaN,NaN,NaN,681,NaN,148,2,2,2
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",NaN,NaN,NaN,347082,NaN,Unknown,True,False,True
freq,NaN,NaN,NaN,1,NaN,NaN,NaN,7,NaN,687,577,814,646
mean,446.000000,0.383838,2.308642,NaN,29.039282,0.426487,0.0,NaN,24.046813,NaN,NaN,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,12.072074,0.708246,0.0,NaN,20.481625,NaN,NaN,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,2.500000,0.000000,0.0,NaN,0.000000,NaN,NaN,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,22.000000,0.000000,0.0,NaN,7.910400,NaN,NaN,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,28.000000,0.000000,0.0,NaN,14.454200,NaN,NaN,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,35.000000,1.000000,0.0,NaN,31.000000,NaN,NaN,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,54.500000,2.500000,0.0,NaN,65.634400,NaN,NaN,NaN,NaN

In [7]:
print(df.columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Name', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Sex_Male', 'Embarked_Q', 'Embarked_S']

In [8]:
print(df.isnull().sum())

PassengerId    0
Survived       0
Pclass         0
Name           0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Sex_Male       0
Embarked_Q     0
Embarked_S     0
dtype: int64

# Selecting Features (X) and Target Variable (y)

In supervised machine learning, the dataset is divided into:

- **X (Features):** Independent variables used to make predictions.
- **y (Target):** The dependent variable that the model learns to predict.

For this project, the target variable is **Survived**, where:

- 0 = Did not survive
- 1 = Survived

In [9]:
# Target variable
y = df["Survived"]

print("Target variable created successfully!")

Target variable created successfully!

In [10]:
# Select useful numerical features
X = df[
    [
        "Pclass",
        "Age",
        "SibSp",
        "Parch",
        "Fare",
        "Sex_Male",
        "Embarked_Q",
        "Embarked_S"
    ]
]

print("Feature matrix created successfully!")

Feature matrix created successfully!

In [11]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (891, 8)
Shape of y: (891,)

In [12]:
X.head()

   Pclass   Age  SibSp  Parch     Fare  Sex_Male  Embarked_Q  Embarked_S
0       3  22.0    1.0      0   7.2500      True       False        True
1       1  38.0    1.0      0  65.6344     False       False       False
2       3  26.0    0.0      0   7.9250     False       False        True
3       1  35.0    1.0      0  53.1000     False       False        True
4       3  35.0    0.0      0   8.0500      True       False        True

In [13]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

# Train-Test Split

Before training a Machine Learning model, the dataset is divided into:

- **Training Set (80%)** → Used to teach the model.
- **Testing Set (20%)** → Used to evaluate the model on unseen data.

Using separate training and testing data helps prevent **data leakage** and provides a more reliable evaluation of the model.

In [16]:
from sklearn.model_selection import train_test_split

print("train_test_split imported successfully!")

train_test_split imported successfully!

In [17]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Dataset split successfully!")

Dataset split successfully!

In [18]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (712, 8)
X_test : (179, 8)
y_train: (712,)
y_test : (179,)

In [19]:
X_train.head()

     Pclass   Age  SibSp  Parch     Fare  Sex_Male  Embarked_Q  Embarked_S
331       1  45.5    0.0      0  28.5000      True       False        True
733       2  23.0    0.0      0  13.0000      True       False        True
382       3  32.0    0.0      0   7.9250      True       False        True
704       3  26.0    1.0      0   7.8542      True       False        True
813       3   6.0    2.5      0  31.2750     False       False        True

In [20]:
X_test.head()

     Pclass   Age  SibSp  Parch     Fare  Sex_Male  Embarked_Q  Embarked_S
709       3  28.0    1.0      0  15.2458      True       False       False
439       2  31.0    0.0      0  10.5000      True       False        True
840       3  20.0    0.0      0   7.9250      True       False        True
720       2   6.0    0.0      0  33.0000     False       False        True
39        3  14.0    1.0      0  11.2417     False       False       False

In [21]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [22]:
y_test.head()

709    1
439    0
840    0
720    1
39     1
Name: Survived, dtype: int64

from sklearn.linear_model import LogisticRegression

print("Logistic Regression imported successfully!")

In [23]:
from sklearn.linear_model import LogisticRegression

print("Logistic Regression imported successfully!")

Logistic Regression imported successfully!

In [24]:
# Initialize the Logistic Regression model

model = LogisticRegression(random_state=42)

print("Model created successfully!")

Model created successfully!

In [25]:
# Train the model using training data

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

d:\VS Code\ProSensia-AI-ML-Internship\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [26]:
# Predict on unseen test data

y_pred = model.predict(X_test)

print("Predictions generated successfully!")

Predictions generated successfully!

In [27]:
print("First 10 Predictions:")
print(y_pred[:10])

First 10 Predictions:
[0 0 0 1 1 1 1 0 1 1]

In [28]:
comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0       1          0
1       0          0
2       0          0
3       1          1
4       1          1
5       1          1
6       1          1
7       0          0
8       1          1
9       1          1

# Model Evaluation

After training the Logistic Regression model, we evaluate its performance using the testing dataset.

The accuracy score measures the percentage of correct predictions made by the model on unseen data.

In [29]:
from sklearn.metrics import accuracy_score

print("Accuracy Score imported successfully!")

Accuracy Score imported successfully!

In [30]:
# Calculate model accuracy

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.7932960893854749

In [31]:
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 79.33%

## Observation

The Logistic Regression model was evaluated using the testing dataset. The accuracy score indicates the percentage of correct predictions made on unseen data.

A higher accuracy generally indicates better predictive performance, but accuracy should be interpreted together with other evaluation metrics depending on the problem.

# Conclusion

In this project, a baseline Logistic Regression model was built using Scikit-Learn.

### Tasks Completed

- Loaded the cleaned and One-Hot Encoded dataset
- Selected the target variable (Survived)
- Created the feature matrix (X) and target vector (y)
- Performed an 80/20 Train-Test split
- Trained the Logistic Regression model using only the training data
- Generated predictions on the testing data
- Calculated the model accuracy

This project introduced the complete workflow for building a basic supervised Machine Learning classification model while following good practices such as avoiding data leakage and evaluating the model using unseen data.